version: 2
updates:
  - package-ecosystem: maven
    directory: /back-end/CC4C
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /front-end/CC4C
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /back-end/CC4C
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /front-end/CC4C
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
