CREATE DATABASE IF NOT EXISTS cc4c_flyway_test
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
    ON cc4c_test.* TO 'cc4c_test_user'@'127.0.0.1';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
    ON cc4c_flyway_test.* TO 'cc4c_test_user'@'127.0.0.1';
